// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PropertyService.Infrastructure.Persistence;

#nullable disable

namespace PropertyService.Infrastructure.Migrations
{
    [DbContext(typeof(PropertyDbContext))]
    [Migration("20251123142857_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PropertyService.Domain.Entities.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Company")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("PropertyType")
                        .HasColumnType("integer")
                        .HasColumnName("property_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("properties", (string)null);
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.PropertyAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address_line2");

                    b.Property<string>("Area")
                        .HasColumnType("text")
                        .HasColumnName("area");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("zip_code");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId")
                        .IsUnique();

                    b.ToTable("property_addresses", (string)null);
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.PropertyFeatured", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId")
                        .IsUnique();

                    b.ToTable("property_featured", (string)null);
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.PropertyLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("latitude");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("longitude");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId")
                        .IsUnique();

                    b.ToTable("property_locations", (string)null);
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.PropertyPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Photo")
                        .HasColumnType("text")
                        .HasColumnName("photo");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("property_photos", (string)null);
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.PropertyRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdditionalRules")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)")
                        .HasColumnName("additional_rules");

                    b.Property<bool>("ArePetsAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("are_pets_allowed");

                    b.Property<TimeOnly>("CheckInTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("check_in_time");

                    b.Property<TimeOnly>("CheckOutTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("check_out_time");

                    b.Property<bool>("IsBachelorFriendly")
                        .HasColumnType("boolean")
                        .HasColumnName("is_bachelor_friendly");

                    b.Property<bool>("IsCoupleFriendly")
                        .HasColumnType("boolean")
                        .HasColumnName("is_couple_friendly");

                    b.Property<bool>("IsIdRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_IdRequired");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId")
                        .IsUnique();

                    b.ToTable("property_rules", (string)null);
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.PropertyStars", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<int>("PropertyStarType")
                        .HasColumnType("integer")
                        .HasColumnName("property_star_type");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId")
                        .IsUnique();

                    b.ToTable("property_stars", (string)null);
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("RoomStatus")
                        .HasColumnType("integer")
                        .HasColumnName("room_status");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_type_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.RoomAmenity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsAirConditioner")
                        .HasColumnType("boolean")
                        .HasColumnName("is_air_conditioner");

                    b.Property<bool>("IsBalcony")
                        .HasColumnType("boolean")
                        .HasColumnName("is_balcony");

                    b.Property<bool>("IsBathTowel")
                        .HasColumnType("boolean")
                        .HasColumnName("is_bath_towel");

                    b.Property<bool>("IsBathtub")
                        .HasColumnType("boolean")
                        .HasColumnName("is_bathtub");

                    b.Property<bool>("IsDentalKit")
                        .HasColumnType("boolean")
                        .HasColumnName("is_dental_kit");

                    b.Property<bool>("IsGeyser")
                        .HasColumnType("boolean")
                        .HasColumnName("is_geyser");

                    b.Property<bool>("IsHairDryer")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hair_dryer");

                    b.Property<bool>("IsMineralWater")
                        .HasColumnType("boolean")
                        .HasColumnName("is_mineral_water");

                    b.Property<bool>("IsRefrigerator")
                        .HasColumnType("boolean")
                        .HasColumnName("is_refrigerator");

                    b.Property<bool>("IsSofa")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sofa");

                    b.Property<bool>("IsToiletries")
                        .HasColumnType("boolean")
                        .HasColumnName("is_toiletries");

                    b.Property<bool>("IsTv")
                        .HasColumnType("boolean")
                        .HasColumnName("is_tv");

                    b.Property<bool>("IsWorkDesk")
                        .HasColumnType("boolean")
                        .HasColumnName("is_work_desk");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.HasKey("Id");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.ToTable("room_amenities", (string)null);
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.RoomType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AdultsCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("adults_capacity");

                    b.Property<double?>("BasePrice")
                        .HasColumnType("double precision")
                        .HasColumnName("base_price");

                    b.Property<int?>("ChildrenCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("children_capacity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<double?>("DiscountPrice")
                        .HasColumnType("double precision")
                        .HasColumnName("discount_price");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("room_types", (string)null);
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.RoomTypeBasicFacility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsCommonRoom")
                        .HasColumnType("boolean")
                        .HasColumnName("is_common_room");

                    b.Property<bool>("IsElevator")
                        .HasColumnType("boolean")
                        .HasColumnName("is_elevator");

                    b.Property<bool>("IsHouseKeeping")
                        .HasColumnType("boolean")
                        .HasColumnName("is_house_keeping");

                    b.Property<bool>("IsLaundryService")
                        .HasColumnType("boolean")
                        .HasColumnName("is_laundry_service");

                    b.Property<bool>("IsLaundryServicePaid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_laundry_service_paid");

                    b.Property<bool>("IsNewsPaper")
                        .HasColumnType("boolean")
                        .HasColumnName("is_news_paper");

                    b.Property<bool>("IsParking")
                        .HasColumnType("boolean")
                        .HasColumnName("is_parking");

                    b.Property<bool>("IsPowerBackup")
                        .HasColumnType("boolean")
                        .HasColumnName("is_power_backup");

                    b.Property<bool>("IsSwimmingPool")
                        .HasColumnType("boolean")
                        .HasColumnName("is_swimming_pool");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_type_id");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId")
                        .IsUnique();

                    b.ToTable("room_type_basic_facilities", (string)null);
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.RoomTypeDiscount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<double>("Rate")
                        .HasColumnType("double precision")
                        .HasColumnName("rate");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_type_id");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("room_type_discounts", (string)null);
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.RoomTypeFoodFacility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsBar")
                        .HasColumnType("boolean")
                        .HasColumnName("is_bar");

                    b.Property<bool>("IsFastingFoodAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fasting_food_available");

                    b.Property<bool>("IsFreeBreakfast")
                        .HasColumnType("boolean")
                        .HasColumnName("is_free_breakfast");

                    b.Property<bool>("IsJain")
                        .HasColumnType("boolean")
                        .HasColumnName("is_jain");

                    b.Property<bool>("IsPureVegetarian")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pure_vegetarian");

                    b.Property<bool>("IsRestaurant")
                        .HasColumnType("boolean")
                        .HasColumnName("is_restaurant");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_type_id");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId")
                        .IsUnique();

                    b.ToTable("room_type_food_facilities", (string)null);
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.RoomTypeOtherFacility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_type_id");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("room_type_other_facilities", (string)null);
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.RoomTypePhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Photo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("photo");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_type_id");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("room_type_photos", (string)null);
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.RoomTypeReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)")
                        .HasColumnName("description");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_type_id");

                    b.Property<int>("Stars")
                        .HasColumnType("integer")
                        .HasColumnName("stars");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("room_type_reviews", (string)null);
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.RoomTypeReviewPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ReviewPhoto")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("review_photo");

                    b.Property<Guid>("RoomTypeReviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_type_review_id");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeReviewId");

                    b.ToTable("room_type_review_photos", (string)null);
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.RoomTypeSecurityFacility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsCctv")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cctv");

                    b.Property<bool>("IsFireExtinguisher")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fire_extinguisher");

                    b.Property<bool>("IsSecurityAlarm")
                        .HasColumnType("boolean")
                        .HasColumnName("is_security_alarm");

                    b.Property<bool>("IsSwimmingPoolSafety")
                        .HasColumnType("boolean")
                        .HasColumnName("is_swimming_pool_safety");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_type_id");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId")
                        .IsUnique();

                    b.ToTable("room_type_security_facilities", (string)null);
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.RoomTypeStaffService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsConcierge")
                        .HasColumnType("boolean")
                        .HasColumnName("is_concierge");

                    b.Property<bool>("IsDoctorOnCall")
                        .HasColumnType("boolean")
                        .HasColumnName("is_doctor_on_call");

                    b.Property<bool>("IsFullDayRoomService")
                        .HasColumnType("boolean")
                        .HasColumnName("is_full_day_room_service");

                    b.Property<bool>("IsLuggageAssist")
                        .HasColumnType("boolean")
                        .HasColumnName("is_luggage_assist");

                    b.Property<bool>("IsWheelchairAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_wheelchair_available");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_type_id");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId")
                        .IsUnique();

                    b.ToTable("room_type_staff_services", (string)null);
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.PropertyAddress", b =>
                {
                    b.HasOne("PropertyService.Domain.Entities.Property", "Property")
                        .WithOne("PropertyAddress")
                        .HasForeignKey("PropertyService.Domain.Entities.PropertyAddress", "PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.PropertyFeatured", b =>
                {
                    b.HasOne("PropertyService.Domain.Entities.Property", "Property")
                        .WithOne("PropertyFeatured")
                        .HasForeignKey("PropertyService.Domain.Entities.PropertyFeatured", "PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.PropertyLocation", b =>
                {
                    b.HasOne("PropertyService.Domain.Entities.Property", "Property")
                        .WithOne("PropertyLocation")
                        .HasForeignKey("PropertyService.Domain.Entities.PropertyLocation", "PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.PropertyPhoto", b =>
                {
                    b.HasOne("PropertyService.Domain.Entities.Property", "Property")
                        .WithMany("PropertyPhotos")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.PropertyRule", b =>
                {
                    b.HasOne("PropertyService.Domain.Entities.Property", "Property")
                        .WithOne("PropertyRule")
                        .HasForeignKey("PropertyService.Domain.Entities.PropertyRule", "PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.PropertyStars", b =>
                {
                    b.HasOne("PropertyService.Domain.Entities.Property", "Property")
                        .WithOne("PropertyStars")
                        .HasForeignKey("PropertyService.Domain.Entities.PropertyStars", "PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.Room", b =>
                {
                    b.HasOne("PropertyService.Domain.Entities.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.RoomAmenity", b =>
                {
                    b.HasOne("PropertyService.Domain.Entities.Room", "Room")
                        .WithOne("RoomAmenity")
                        .HasForeignKey("PropertyService.Domain.Entities.RoomAmenity", "RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.RoomType", b =>
                {
                    b.HasOne("PropertyService.Domain.Entities.Property", "Property")
                        .WithMany("RoomTypes")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.RoomTypeBasicFacility", b =>
                {
                    b.HasOne("PropertyService.Domain.Entities.RoomType", "RoomType")
                        .WithOne("RoomTypeBasicFacility")
                        .HasForeignKey("PropertyService.Domain.Entities.RoomTypeBasicFacility", "RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.RoomTypeDiscount", b =>
                {
                    b.HasOne("PropertyService.Domain.Entities.RoomType", "RoomType")
                        .WithMany("RoomTypeDiscounts")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.RoomTypeFoodFacility", b =>
                {
                    b.HasOne("PropertyService.Domain.Entities.RoomType", "RoomType")
                        .WithOne("RoomTypeFoodFacility")
                        .HasForeignKey("PropertyService.Domain.Entities.RoomTypeFoodFacility", "RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.RoomTypeOtherFacility", b =>
                {
                    b.HasOne("PropertyService.Domain.Entities.RoomType", "RoomType")
                        .WithMany("RoomTypeOtherFacilities")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.RoomTypePhoto", b =>
                {
                    b.HasOne("PropertyService.Domain.Entities.RoomType", "RoomType")
                        .WithMany("RoomTypePhotos")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.RoomTypeReview", b =>
                {
                    b.HasOne("PropertyService.Domain.Entities.RoomType", "RoomType")
                        .WithMany("RoomTypeReviews")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.RoomTypeReviewPhoto", b =>
                {
                    b.HasOne("PropertyService.Domain.Entities.RoomTypeReview", "RoomTypeReview")
                        .WithMany("RoomTypeReviewPhotos")
                        .HasForeignKey("RoomTypeReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomTypeReview");
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.RoomTypeSecurityFacility", b =>
                {
                    b.HasOne("PropertyService.Domain.Entities.RoomType", "RoomType")
                        .WithOne("RoomTypeSecurityFacility")
                        .HasForeignKey("PropertyService.Domain.Entities.RoomTypeSecurityFacility", "RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.RoomTypeStaffService", b =>
                {
                    b.HasOne("PropertyService.Domain.Entities.RoomType", "RoomType")
                        .WithOne("RoomTypeStaffService")
                        .HasForeignKey("PropertyService.Domain.Entities.RoomTypeStaffService", "RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.Property", b =>
                {
                    b.Navigation("PropertyAddress");

                    b.Navigation("PropertyFeatured");

                    b.Navigation("PropertyLocation");

                    b.Navigation("PropertyPhotos");

                    b.Navigation("PropertyRule");

                    b.Navigation("PropertyStars");

                    b.Navigation("RoomTypes");
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.Room", b =>
                {
                    b.Navigation("RoomAmenity");
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.RoomType", b =>
                {
                    b.Navigation("RoomTypeBasicFacility");

                    b.Navigation("RoomTypeDiscounts");

                    b.Navigation("RoomTypeFoodFacility");

                    b.Navigation("RoomTypeOtherFacilities");

                    b.Navigation("RoomTypePhotos");

                    b.Navigation("RoomTypeReviews");

                    b.Navigation("RoomTypeSecurityFacility");

                    b.Navigation("RoomTypeStaffService");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("PropertyService.Domain.Entities.RoomTypeReview", b =>
                {
                    b.Navigation("RoomTypeReviewPhotos");
                });
#pragma warning restore 612, 618
        }
    }
}
