// <auto-generated />
using System;
using BookingService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookingService.Infrastructure.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    partial class BookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookingService.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Adults")
                        .HasColumnType("integer")
                        .HasColumnName("adults");

                    b.Property<Guid>("BookingGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_group_id");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_in_date");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_out_date");

                    b.Property<int>("Children")
                        .HasColumnType("integer")
                        .HasColumnName("children");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cancelled");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.HasKey("Id");

                    b.HasIndex("BookingGroupId");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("BookingService.Domain.Entities.BookingGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_in_date");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_out_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("booking_groups", (string)null);
                });

            modelBuilder.Entity("BookingService.Domain.Entities.BookingGroupAmount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("ActualAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("actual_amount");

                    b.Property<Guid>("BookingGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_group_id");

                    b.Property<decimal>("DiscountedAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("discounted_amount");

                    b.Property<bool>("IsCouponApplicable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_coupon_applicable");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("total_amount");

                    b.HasKey("Id");

                    b.HasIndex("BookingGroupId")
                        .IsUnique();

                    b.ToTable("booking_group_amounts", (string)null);
                });

            modelBuilder.Entity("BookingService.Domain.Entities.BookingGroupAmountCoupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingGroupAmountId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_group_amount_id");

                    b.Property<Guid>("CouponId")
                        .HasColumnType("uuid")
                        .HasColumnName("coupon_id");

                    b.HasKey("Id");

                    b.HasIndex("BookingGroupAmountId");

                    b.HasIndex("CouponId");

                    b.ToTable("booking_group_amount_coupons", (string)null);
                });

            modelBuilder.Entity("BookingService.Domain.Entities.BookingGroupHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_group_id");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<int>("NewStatus")
                        .HasColumnType("integer")
                        .HasColumnName("new_status");

                    b.Property<int>("OldStatus")
                        .HasColumnType("integer")
                        .HasColumnName("old_status");

                    b.HasKey("Id");

                    b.HasIndex("BookingGroupId");

                    b.ToTable("booking_group_histories", (string)null);
                });

            modelBuilder.Entity("BookingService.Domain.Entities.BookingGuest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("booking_guests", (string)null);
                });

            modelBuilder.Entity("BookingService.Domain.Entities.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("code");

                    b.Property<int>("CouponType")
                        .HasColumnType("integer")
                        .HasColumnName("coupon_type");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric")
                        .HasColumnName("discount");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.ToTable("coupons", (string)null);
                });

            modelBuilder.Entity("BookingService.Domain.Entities.Booking", b =>
                {
                    b.HasOne("BookingService.Domain.Entities.BookingGroup", "BookingGroup")
                        .WithMany("Bookings")
                        .HasForeignKey("BookingGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookingGroup");
                });

            modelBuilder.Entity("BookingService.Domain.Entities.BookingGroupAmount", b =>
                {
                    b.HasOne("BookingService.Domain.Entities.BookingGroup", "BookingGroup")
                        .WithOne("BookingGroupAmount")
                        .HasForeignKey("BookingService.Domain.Entities.BookingGroupAmount", "BookingGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookingGroup");
                });

            modelBuilder.Entity("BookingService.Domain.Entities.BookingGroupAmountCoupon", b =>
                {
                    b.HasOne("BookingService.Domain.Entities.BookingGroupAmount", "BookingGroupAmount")
                        .WithMany("BookingGroupAmountCoupons")
                        .HasForeignKey("BookingGroupAmountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingService.Domain.Entities.Coupon", "Coupon")
                        .WithMany("BookingGroupAmountCoupons")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookingGroupAmount");

                    b.Navigation("Coupon");
                });

            modelBuilder.Entity("BookingService.Domain.Entities.BookingGroupHistory", b =>
                {
                    b.HasOne("BookingService.Domain.Entities.BookingGroup", "BookingGroup")
                        .WithMany("BookingGroupHistories")
                        .HasForeignKey("BookingGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookingGroup");
                });

            modelBuilder.Entity("BookingService.Domain.Entities.BookingGuest", b =>
                {
                    b.HasOne("BookingService.Domain.Entities.Booking", "Booking")
                        .WithMany("BookingGuests")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("BookingService.Domain.Entities.Booking", b =>
                {
                    b.Navigation("BookingGuests");
                });

            modelBuilder.Entity("BookingService.Domain.Entities.BookingGroup", b =>
                {
                    b.Navigation("BookingGroupAmount");

                    b.Navigation("BookingGroupHistories");

                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("BookingService.Domain.Entities.BookingGroupAmount", b =>
                {
                    b.Navigation("BookingGroupAmountCoupons");
                });

            modelBuilder.Entity("BookingService.Domain.Entities.Coupon", b =>
                {
                    b.Navigation("BookingGroupAmountCoupons");
                });
#pragma warning restore 612, 618
        }
    }
}
